apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: sporttrade-app
  name: sporttrade-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sporttrade-app
  template:
    metadata:
      labels:
        app: sporttrade-app
    spec:
      containers:
      - name: my-sporttrade-app
        image: kuga01/javacalculator:2a6a77d
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        volumeMounts:
        - mountPath: /var/lib/sporttrade-log/
          name: storage-volume
      volumes:
      - name: storage-volume
        hostPath:
          path: /var/lib/sporttrade
          type: DirectoryOrCreate
